/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl1;

import java.util.concurrent.atomic.AtomicInteger;

/**
 *
 * @author daniel
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    private Hawkins hawkins;
    private UpsideDown upsideDown;
    private GestorEventos gestor;
    private AtomicInteger contadorNiños;
    public Interfaz() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(15, 15, 15));
    
        // Cambiar fuente de los títulos grandes a algo más "retro"
        java.awt.Font retroFont = new java.awt.Font("Courier New", java.awt.Font.BOLD, 36);
        jLabel1.setFont(retroFont); jLabel1.setForeground(java.awt.Color.RED);
        jLabel2.setFont(retroFont); jLabel2.setForeground(new java.awt.Color(154, 48, 255));
        jLabel3.setFont(retroFont); jLabel3.setForeground(new java.awt.Color(255, 102, 0)); // Rojo oscuro
        jLabel4.setFont(retroFont); jLabel4.setForeground(new java.awt.Color(57, 255, 20)); // Rojo oscuro
        sangre.setForeground(java.awt.Color.RED); // Rojo oscuro

        // Blanco sucio / grisáceo
        java.awt.Color labelColor = new java.awt.Color(200, 200, 200);
        jLabel5.setForeground(labelColor);   // CALLE PRINCIPAL
        jLabel6.setForeground(labelColor);   // SOTANO BYERS
        jLabel7.setForeground(labelColor);   // RADIO WSQK
        jLabel8.setForeground(labelColor);   // PORTAL BOSQUE
        jLabel9.setForeground(labelColor);   // PORTAL LABORATORIO
        jLabel10.setForeground(labelColor);  // PORTAL CENTRO COMERCIAL
        jLabel11.setForeground(labelColor);  // PORTAL ALCANTARILLADO
        jLabel12.setForeground(labelColor);  // CENTRO COMERCIAL
        jLabel13.setForeground(labelColor);  // LABORATORIO
        jLabel14.setForeground(labelColor);  // ALCANTARILLADO
        jLabel15.setForeground(labelColor);  // BOSQUE
        jLabel16.setForeground(labelColor);  // NIÑOS
        jLabel19.setForeground(labelColor);  // DEMOGORGONS
        jLabel20.setForeground(labelColor);  // DEMOGORGONS
        jLabel21.setForeground(labelColor);  // DEMOGORGONS

        // Estos dos aparte por ser especiales
        jLabel17.setForeground(java.awt.Color.RED);                        // SANGRE
        jLabel18.setForeground(new java.awt.Color(255, 200, 0));           // EVENTO EN CURSO
        demogorgons.setForeground(java.awt.Color.RED);                        // Contador de Demogorgons
        cantidadNiñosColmena.setForeground(java.awt.Color.RED);                        // Contador de Demogorgons


    }
    
    public void setInicial(Hawkins h, UpsideDown u, GestorEventos g, AtomicInteger a){
        this.hawkins = h;
        this.upsideDown = u;
        this.gestor = g;
        this.contadorNiños = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        callePrincipal = new javax.swing.JTextField();
        radioWSQK = new javax.swing.JTextField();
        sotanoByers = new javax.swing.JTextField();
        portalLaboratorio = new javax.swing.JTextField();
        portalAlcantarillado = new javax.swing.JTextField();
        portalBosque = new javax.swing.JTextField();
        portalCentroComercial = new javax.swing.JTextField();
        bosque = new javax.swing.JTextField();
        laboratorio = new javax.swing.JTextField();
        alcantarillado = new javax.swing.JTextField();
        centroComercial = new javax.swing.JTextField();
        niñosColmena = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        sangre = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        evento = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        demogorgons = new javax.swing.JLabel();
        cantidadNiñosColmena = new javax.swing.JLabel();
        niños = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("HAWKINS");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel2.setText("PORTALES");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setText("UPSIDE DOWN");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel4.setText("COLMENA");

        jLabel5.setText("CALLE PRINCIPAL");

        jLabel6.setText("SOTANO BYERS");

        jLabel7.setText("RADIO WSQK");

        jLabel8.setText("PORTAL BOSQUE");

        jLabel9.setText("PORTAL LABORATORIO");

        jLabel10.setText("PORTAL CENTRO COMERCIAL");

        jLabel11.setText("PORTAL ALCANTARILLADO");

        jLabel12.setText("CENTRO COMERCIAL");

        jLabel13.setText("LABORATORIO");

        jLabel14.setText("ALCANTARILLADO");

        jLabel15.setText("BOSQUE");

        jLabel16.setText("NIÑOS");

        callePrincipal.setText("jTextField1");
        callePrincipal.setPreferredSize(new java.awt.Dimension(200, 24));
        callePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callePrincipalActionPerformed(evt);
            }
        });

        radioWSQK.setText("jTextField1");
        radioWSQK.setPreferredSize(new java.awt.Dimension(200, 24));
        radioWSQK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioWSQKActionPerformed(evt);
            }
        });

        sotanoByers.setText("jTextField1");
        sotanoByers.setPreferredSize(new java.awt.Dimension(200, 24));

        portalLaboratorio.setText("jTextField1");
        portalLaboratorio.setPreferredSize(new java.awt.Dimension(200, 24));

        portalAlcantarillado.setText("jTextField1");
        portalAlcantarillado.setPreferredSize(new java.awt.Dimension(200, 24));

        portalBosque.setText("jTextField1");
        portalBosque.setPreferredSize(new java.awt.Dimension(200, 24));

        portalCentroComercial.setText("jTextField1");
        portalCentroComercial.setPreferredSize(new java.awt.Dimension(200, 24));

        bosque.setText("jTextField1");
        bosque.setPreferredSize(new java.awt.Dimension(200, 24));

        laboratorio.setText("jTextField1");
        laboratorio.setPreferredSize(new java.awt.Dimension(200, 24));
        laboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioActionPerformed(evt);
            }
        });

        alcantarillado.setText("jTextField1");
        alcantarillado.setPreferredSize(new java.awt.Dimension(200, 24));

        centroComercial.setText("jTextField1");
        centroComercial.setPreferredSize(new java.awt.Dimension(200, 24));

        niñosColmena.setText("jTextField1");
        niñosColmena.setPreferredSize(new java.awt.Dimension(200, 24));

        jLabel17.setText("SANGRE");

        sangre.setText("jLabel18");

        jLabel18.setText("EVENTO EN CURSO");
        jLabel18.setPreferredSize(new java.awt.Dimension(150, 40));

        evento.setText("jTextField1");

        jLabel19.setText("DEMOGORGONS");

        demogorgons.setText("jLabel20");

        cantidadNiñosColmena.setText("jLabel20");

        niños.setText("jLabel20");

        jLabel20.setText("NIÑOS");

        jLabel21.setText("ULTIMO EVENTO");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(callePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)
                        .addComponent(radioWSQK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sotanoByers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sangre)
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(niños))))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addComponent(portalBosque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(portalLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(portalAlcantarillado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(portalCentroComercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(bosque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(laboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alcantarillado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centroComercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(niñosColmena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(demogorgons)
                    .addComponent(cantidadNiñosColmena)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(evento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cantidadNiñosColmena))
                        .addGap(99, 99, 99)
                        .addComponent(jLabel14)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addComponent(jLabel8)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel9)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel11)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(callePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(portalBosque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bosque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(niñosColmena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(portalLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54)
                                        .addComponent(sotanoByers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(portalAlcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel12))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioWSQK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(portalCentroComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(centroComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(demogorgons)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sangre)
                    .addComponent(niños))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioWSQKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioWSQKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioWSQKActionPerformed

    private void callePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callePrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_callePrincipalActionPerformed

    private void laboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorioActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    public void actualizarDatos(){
        callePrincipal.setText(hawkins.getCallePrincipal().getNiños().toString());
        sotanoByers.setText(hawkins.getSotanoByers().getNiños().toString());
        radioWSQK.setText(hawkins.getRadioWSBK().getNiños().toString());
        sangre.setText(hawkins.getRadioWSBK().getSangre() + "");
        bosque.setText(upsideDown.getBosque().getNiños().toString());
        laboratorio.setText(upsideDown.getLaboratorio().getNiños().toString());
        alcantarillado.setText(upsideDown.getAlcantarillado().getNiños().toString());
        centroComercial.setText(upsideDown.getCentroComercial().getNiños().toString());
        niñosColmena.setText(upsideDown.getColmena().getNiños().toString());
        portalBosque.setText(hawkins.getSotanoByers().getPortalBosque().getNiños().toString());
        portalLaboratorio.setText(hawkins.getSotanoByers().getPortalLaboratorio().getNiños().toString());
        portalAlcantarillado.setText(hawkins.getSotanoByers().getPortalAlcantarillado().getNiños().toString());
        portalCentroComercial.setText(hawkins.getSotanoByers().getPortalCentroComercial().getNiños().toString());
        evento.setText(gestor.getEvento());
        demogorgons.setText(upsideDown.getContadorDemogorgons() + "");
        cantidadNiñosColmena.setText(upsideDown.getColmena().getCantidadNiños() + "");
        niños.setText(contadorNiños.get() + "");
        jTextField1.setText(gestor.getUltimoEventoActivo());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alcantarillado;
    private javax.swing.JTextField bosque;
    private javax.swing.JTextField callePrincipal;
    private javax.swing.JLabel cantidadNiñosColmena;
    private javax.swing.JTextField centroComercial;
    private javax.swing.JLabel demogorgons;
    private javax.swing.JTextField evento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField laboratorio;
    private javax.swing.JLabel niños;
    private javax.swing.JTextField niñosColmena;
    private javax.swing.JTextField portalAlcantarillado;
    private javax.swing.JTextField portalBosque;
    private javax.swing.JTextField portalCentroComercial;
    private javax.swing.JTextField portalLaboratorio;
    private javax.swing.JTextField radioWSQK;
    private javax.swing.JLabel sangre;
    private javax.swing.JTextField sotanoByers;
    // End of variables declaration//GEN-END:variables
}
